// Generates placeholder PNG icons (1x1 transparent) for PWA so manifest stops 404s.
// Replace with real artwork later.
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const pubDir = path.join(__dirname, '..', 'public');

const icons = [
  { file: 'icon-192.png', b64: 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5QYcDxow3VhLEwAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAABTElEQVR42u3TMQ0AIAzAMMC/52YMFQazQtcgqG3wJW7A+f4DAQIECBAgQIAAAQIECBAgQOD/wZbX1nrbP8nf97XW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2lvW2kve4CDnyvw4AQIECBAgQIAAAQIECBAg8B8CKxsAAa4TuEwAAAAASUVORK5CYII=' },
  { file: 'icon-512.png', b64: 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5QYcDxo2KbJQigAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAABYklEQVR42u3QMQEAAAgDINc/9K3hAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDnBXmYAQIECBAgQIAAAQIECBAgQODfB5hGAAERejHXAAAAAElFTkSuQmCC' }
];

icons.forEach(({ file, b64 }) => {
  const outPath = path.join(pubDir, file);
  const buf = Buffer.from(b64, 'base64');
  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, buf);
  console.log('Wrote', outPath, buf.length, 'bytes');
});

console.log('Placeholder icons generated. Replace with real assets later.');